### ISSUE TITLE
Clicking close button on maximized graph does not close the graph

### ISSUE THREAD

**Issue by robvdw2** [BrewBlox/brewblox-ui#1375]
When clicking the close button on a maximized graph or subprocess graph (from session log), it does not close the maximized graph. Using Escape on the keyboard does successfully close it. 
The problem does not occur with PID graphs.

Here's a quick screen cap to illustrate:
![Peek 2020-08-01 12-15](https://user-images.githubusercontent.com/15369410/89099955-6ac48880-d3f3-11ea-8a94-e66033192cd4.gif)

Tested on Firefox 78 and Chrome 83, the UI logs file is empty.  Brewblox is fully updated to the latest version.

PS: I don't know if you prefer to receive bug reports on the discourse or here. Let me know if this is not the appropriate place.

Rob

**Comment by steersbob** [comment]
The issue reproduces here, and will be fixed in next release.

We use GitHub issues to track repo-specific bugs/tasks. This is a UI-specific bug, so GitHub issues is very much appropriate.
For bugs or requests that concern multiple repositories, the forum is probably easier. We'll then split it into issues for each relevant repository.
